when:
  instance: ci.kokuwa.io
  event: [manual, pull_request]
  path: [.woodpecker/verify.yaml, pom.xml, src/**]

steps:

  maven:
    image: maven:3.9.11-eclipse-temurin-17
    commands: mvn verify --settings=.woodpecker/maven/settings.xml

  git:
    image: maven:3.9.11-eclipse-temurin-17
    commands: .woodpecker/maven/git-check.sh
